services:
  - type: web
    name: topaz-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w ${WEB_CONCURRENCY:-2} -b 0.0.0.0:${PORT} main:app --log-level ${LOG_LEVEL:-info} --forwarded-allow-ips "*" --proxy-headers
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: API_AUTH_KEY
        value: doom-blocker-extension-api-key-2024
      - key: ENV
        value: production
      - key: CORS_ORIGINS
        value: https://www.doomblocker.com,https://internetfilter.org
      - key: TRUSTED_HOSTS
        value: topaz-backend1.onrender.com,www.doomblocker.com,internetfilter.org
      - key: LOG_LEVEL
        value: info